### 로그인 검증 요청

POST http://localhost:8085/auth/login
Content-Type: application/json

{
  "email" : "kk1@naver.com",
  "password" : "1234"
}
### 로그인 검증 요청

GET http://localhost:8085/test
Content-Type: application/json
Cookie: SESSION=22774612-a73d-48f0-bd75-dfdd60c0e457
